# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_item',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
