# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160304_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_item',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
